# Cirrus CI configuration
# https://cirrus-ci.com/github/dfandrich/gpscorrelate

task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
      image: freebsd-10-4-release-amd64

  env:
    CIRRUS_CLONE_DEPTH: 1
    CFLAGS: -Wall -Wextra -Werror -O3 -DENABLE_NLS=1
    LDFLAGS: $CFLAGS -lintl
    CC: cc
    CXX: c++
    MAKE_FLAGS: -j 2
  pkginstall_script:
    - pkg install -y pkgconf docbook exiv2 libxml2 gtk2 libxslt gettext-tools desktop-file-utils gmake

  compile_script:
    # TODO: use make instead of gmake
    - gmake CC="$CC" CXX="$CXX" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
  test_script:
    - ./gpscorrelate -V
    # The tests involving writing to read-only files fail when run as root
    # (because the OS allows the files to be overwritten then). Run the
    # tests as a normal user to get around that problem. The log directory
    # must be world-writable since files will be written there.
    - install -d -m 0777 tests/log
    - sudo -u nobody gmake check
  install_script:
    - gmake prefix= DESTDIR="${HOME}" install install-po install-desktop-file
