# Travis CI configuration file

sudo: false

language: cpp

git:
  depth: 1

# Install needed packages on Ubuntu (OS X is done with brew below)
addons:
  apt:
    packages:
        - desktop-file-utils
        - exiv2
        - libexiv2-dev
        - libgtk2.0-dev

install:
  # Install exiv2 on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install desktop-file-utils exiv2 gtk+; fi
  - if [ "$CONFIG" = "coverage" ] ; then pip install --user cpp-coveralls; fi
  - |
    if [ "$CONFIG" = "musl" ] ; then
      echo "FROM alpine" > Dockerfile
      echo "RUN apk add --no-cache build-base exiv2-dev libxml2-dev gettext-dev gtk+2.0-dev desktop-file-utils" >> Dockerfile
      echo "RUN adduser -D -u $(id -u) build" >> Dockerfile
      docker build -t alpine-build .
    fi

env:
  # More configurations are configured in the matrix section
  matrix:
    - CONFIG=normal
    - CONFIG=no_nls
    - CONFIG=sanitize
  global:
    - MAKEFLAGS='-j 2'

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  exclude:
  # Gives spurious errors with clang and gcc doesn't support -fsanitize=undefined
  - env: CONFIG=sanitize  # Gives spurious errors in this config
    os: linux
  include:
  # Only run the coverage build in one configuration
  - env: CONFIG=coverage
    os: linux
    compiler: gcc
  - env: CONFIG=clang6
    os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-6.0
          - ubuntu-toolchain-r-test
        packages:
          - desktop-file-utils
          - exiv2
          - libexiv2-dev
          - libgtk2.0-dev
          - clang-6.0
    compiler: clang
  - env: CONFIG=gcc8
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - desktop-file-utils
          - exiv2
          - libexiv2-dev
          - libgtk2.0-dev
          - g++-8
    compiler: gcc
  - env: CONFIG=musl
    os: linux
    sudo: required
    services: docker

# Only build the command-line tool for now
script:
  - TARGET='gpscorrelate gpscorrelate-gui'
  - if [ "$CONFIG" = "normal" ] ; then CFLAGS='-Wall -Wextra -Werror -O3 -DENABLE_NLS=1'; fi
  - if [ "$CONFIG" = "no_nls" ] ; then CFLAGS='-Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "sanitize" ] ; then CFLAGS='-g -O0 -fsanitize=address -fsanitize=undefined -DENABLE_NLS=1'; LDFLAGS='$(CFLAGS)'; fi
    # FIXME: There are no tests for the GUI, so don't bother building it.
  - if [ "$CONFIG" = "coverage" ] ; then CFLAGS='-g -O0 --coverage'; LDFLAGS='$(CFLAGS)'; TARGET='gpscorrelate'; fi
  - if [ "$CONFIG" = "clang6" ] ; then CFLAGS='-Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3 -DENABLE_NLS=1'; CC=clang-6.0; CXX=clang++-6.0; fi
  - if [ "$CONFIG" = "gcc8" ] ; then CFLAGS='-Wall -Wextra -Werror -O3 -DENABLE_NLS=1'; CC=gcc-8; CXX=g++-8; fi

    # Explicitly point to brew's gettext installation on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then CFLAGS="$CFLAGS -I/usr/local/opt/gettext/include"; LDFLAGS="$LDFLAGS -L/usr/local/opt/gettext/lib -lintl"; fi

  - |
    if [ "$CONFIG" = "musl" ] ; then
      docker run --rm -v "$PWD":/tmp/src alpine-build sh -c '
        cat /etc/os-release
        # Some tests fail if run as root (the ones to do with read only files)
        su -l build -c "
          set -ex
          cd /tmp/src
          make CFLAGS=-DENABLE_NLS LDFLAGS=-lintl gpscorrelate gpscorrelate-gui
          ./gpscorrelate -V
          make check
          make install-po install-desktop-file prefix= DESTDIR="\${HOME}"
          "
        '
    else
      make CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" CC="$CC" CXX="$CXX" $TARGET
     ./gpscorrelate -V
      make check
    # This can only be installed if the GTK target is also built
    #   make install DESTDIR="${HOME}"
    # Ensure brew gettext is in the PATH so xgettext is found on OS X
      PATH="$PATH:/usr/local/opt/gettext/bin" make install-po install-desktop-file prefix= DESTDIR="${HOME}"
    fi

after_success:
  - if [ "$CONFIG" = "coverage" ] ; then coveralls --gcov-options '\-lp'; fi
